### ISSUE TITLE
An improper locking due to the unreleased lock before program exit

### ISSUE THREAD

**Issue by ryancaicse** [jhrozek/uid_wrapper#1]
Hi developers, in the below codes, the lock` uwrap_id_mutex` could be not released before program's exit `exit(-1);`  . I think there is no harm to write  `pthread_mutex_unlock(&uwrap_id_mutex);`  before the `exit(-1);`  for better resource management and code symmetry. Thanks!

https://github.com/jhrozek/uid_wrapper/blob/d64e5685df006782866f6470747c58c873ff5f60/src/uid_wrapper.c#L592-L613

Best,

**Comment by jhrozek** [comment]
This is just my personal for of uid_wrapper and frankly I haven't been contributing to it in some years. Please go to cwrap.org, there's a 'report a bug' button.
